image: openjdk:11-jdk

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - test

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

test:
  stage: test
  script:
    - ./gradlew check
